# -*- coding: utf-8 -*-
"""Studentdataanalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmRR-0J9KRxfYx9TIkG6xaSNwLeJ9UKX
"""

students=[
    {"name":"Ali","Score":92},
    {"name":"Sara","Score":76},
    {"name":"Ahmed","Score":61},
    {"name":"Hina","Score":43},
    {"name":"Zoya","Score":88},
    {"name":"Afsha","Score":32},
    {"name":"noor","Score":96},
    {"name":"farhan","Score":68},
    {"name":"Hifza","Score":49},
    {"name":"Zohaib","Score":23}
    ]
high=[]
Medium=[]
low=[]
failed=[]
scores=[]

for student in students:

  scores.append(student["Score"])

  if student ["Score"] >=80:
        high.append(student["name"])


  elif student["Score"] >=60:
        Medium.append(student["name"])


  elif student ["Score"]  >=40:
        low.append(student["name"])


  else:
        failed.append(student["name"])
user = input("Enter student name: ")

for student in students:
   if student["name"]==user:
     print("Student name:",student["name"])
     print("Student Score:",student["Score"])
if student["Score"] >=80:
        print("Grade: A")
elif student["Score"] >=60:
        print("Grade: B")
elif student ["Score"]  >=40:
        print("Grade: C")
else:
        print("Grade: F")